### ISSUE TITLE
Tags error

### ISSUE THREAD

**Issue by ThAlmighty** [rodo/osrm-profiles#3]
Hey there,

I run into this error when using the `truck.lua` profile

```
terminate called after throwing an instance of 'osrm::exception'
  what():  ERROR occured in profile script:
profile.lua:77: attempt to index field 'tags' (a nil value)
```

**Comment by tiagofassoni** [comment]
I've had the same issue trying to use ibikecph's green.lua routing profile.

I've had to change: 
```lua
local barrier = node.tags:Find("barrier")
```
to
```lua
  local barrier = node:get_value_by_key("barrier")
```

Which is the new standard in the default bicycle.lua profile

**Comment by quentin9696** [comment]
Hello, 

I can fix it if you want. 

Quentin.

**Comment by rodo** [comment]
PR are always welcome
